#pragma once

void initLoginMenu();
void initRegisterMenu();
void initUserMenu();
void initAdminMenu();
void initStartMenu();
void initDataTypeMenu();
void initRegisterConfirmationMenu();
void initAuthorListMenu();
void initDocumentListMenu();
void initReaderListMenu();
void initPublisherListMenu();
void initUserListMenu();
void initLogMenu();
void initDocumentGivingMenu();
void initReaderDebtListMenu();
void menuInitAll();
void menuControlLoop();
void menuPrintLoop();